# Generated by Django 4.1.3 on 2022-11-27 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_is_staff_alter_user_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
