# Generated by Django 4.1.3 on 2022-11-27 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_staff'),
        ('user', '0007_alter_user_birth_date'),
    ]

    operations = [
    ]
